Script started on Fri Nov  6 11:00:23 2015
[?1034hbash-3.2$ cd rshell
bash-3.2$ make
g++ -c -Wall -Werror -ansi -pedantic rshell.cpp 
g++ rshell.o -o rshell 
bash-3.2$ ./rshell
rshell$ mak   ls #-a
Makefile	rshell		rshell.cpp	rshell.o
rshell$ ls -a
.		.DS_Store	Makefile	rshell.cpp
..		.git		rshell		rshell.o
rshell$ echo helloworld! #bybye world
helloworld!
rshell$ #none of this will show
rshell$ echo hello #kjnfalkjesnflu4n2943nrfrkjnslfgjfngfdj
hello
rshell$ echo thiswillshow #&& none of this ||              ||   || ; end exit        exit clear ls
thiswillshow
rshell$ #exit
rshell$ exit
bash-3.2$ exit
exit

Script done on Fri Nov  6 11:01:48 2015
